### ISSUE TITLE
数学I小错误

### ISSUE THREAD

**Issue by liyongsea** [OpenLMLab/GAOKAO-Bench#10]
https://github.com/OpenLMLab/GAOKAO-Bench/blob/main/data/Multiple-choice_Questions/2010-2022_Math_I_MCQs.json#LL18C29-L18C184
2010年新课标数学I第二题
(5 分) 已知复数 $z=\\frac{\\sqrt{3}+i}{(1-\\sqrt{3} i)^{2}}, \\bar{z}$ 是 $z$ 的共轭复数, 则 $z=\\bar{z}=(\\quad)$\nA. $\\frac{1}{4}$\nB. $\\frac{1}{2}$\nC. 1\nD. 2\n"

应该是z \\cdot \\bar{z}

(5 分) 已知复数 $z=\\frac{\\sqrt{3}+i}{(1-\\sqrt{3} i)^{2}}, \\bar{z}$ 是 $z$ 的共轭复数, 则 $z \\cdot \\bar{z}=(\\quad)$\nA. $\\frac{1}{4}$\nB. $\\frac{1}{2}$\nC. 1\nD. 2\n"

**Comment by xpqiu** [comment]
@zzzyyi @luchyy

**Comment by zzzyyi** [comment]
Thanks for your correction! We have modified it :)
