### ISSUE TITLE
数据收集过程

### ISSUE THREAD

**Issue by Richar-Du** [OpenLMLab/GAOKAO-Bench#13]
感谢您的工作，为评估大模型提供了一个很棒的基准！

想请问一下高考题是如何收集的呢？我看到网上大部分的网站都是付费下载，并且是扫描版的格式，请问您都是手动下载并且人工做的数据处理吗？

**Comment by luchyy** [comment]
您好，高考历年真题在网络上有免费的下载源，之后使用python脚本抽取题目
