### ISSUE TITLE
Solution of "Exception: list index out of range" when run `python choice_bench.py`

### ISSUE THREAD

**Issue by voyager0003** [OpenLMLab/GAOKAO-Bench#18]
I meet this and spent 10mins to fig it out. now I will show you the reason and solution.  

### Issue
when you following the README.md and run `python choice_bench.py`, you may meet following error and the program loop endlessly
![image](https://github.com/OpenLMLab/GAOKAO-Bench/assets/15920086/9cee3931-940f-4569-b107-26297d618c1a)

### Reason
the regex pattern ends with a "\n", in line 16 of "GAOKAO-Bench/Bench/bench_function.py".
so if you don't add a "\n" in "GAOKAO-Bench/data/my_openai_apikey.txt", then the regex match failed.

### Solution
just add a "\n" (press Enter of your keyboard) at the end of "GAOKAO-Bench/data/my_openai_apikey.txt"

**Comment by zzzyyi** [comment]
Thank you for your contribution!
