### ISSUE TITLE
json. decoder.JSONDecodeError: Invalid escape: 

### ISSUE THREAD

**Issue by zyy-2001** [OpenLMLab/GAOKAO-Bench#19]
error:
![32ef96412c37dc4ce5507b792a97de9](https://github.com/OpenLMLab/GAOKAO-Bench/assets/73881472/2f300ea0-b792-4d89-9fa2-90659e9c62d5)
solution:
clearly, escape character, the error position is in 2010-2022_Math_I_MCQs.json related with the question "question": "2. (5 分) 已知复数 $z=\\frac{\\sqrt{3}+i}{(1-\\sqrt{3} i)^{2}}, \\bar{z}$ 是 $z$ 的共轭复数, 则 $z=\\cdot\bar{z}=(\\quad)$\nA. $\\frac{1}{4}$\nB. $\\frac{1}{2}$\nC. 1\nD. 2\n"
delete it or replace it to "question": "2. (5 分) 已知复数 $z=\\frac{\\sqrt{3}+i}{(1-\\sqrt{3} i)^{2}}, \\bar{z}$ 是 $z$ 的共轭复数, 则 $z=\\\cdot\bar{z}=(\\quad)$\nA. $\\frac{1}{4}$\nB. $\\frac{1}{2}$\nC. 1\nD. 2\n"
or \cdot -> \\\cdot

**Comment by Dionysusssss** [comment]
Same error.

**Comment by Dionysusssss** [comment]
Try replace all '\cdot' to '\\cdot'. I have Fix that error, but don't know why?

**Comment by karry12138** [comment]
同样的问题，在json处理的过程中因同样的报错发现。希望能够修正这个数据的错误：\c -> \\\c
/GAOKAO-Bench/data/Multiple-choice_Questions/2010-2022_Math_I_MCQs.json  line 18  column 114
![数据错误1 少了反斜杠](https://github.com/OpenLMLab/GAOKAO-Bench/assets/66634899/ff823f32-1e1f-49ad-ab0b-b0338ad6daee)

**Comment by zzzyyi** [comment]
Thank you for your report! We've fixed the error in [this line](https://github.com/OpenLMLab/GAOKAO-Bench/blob/e4c84266523df2b4152893a8ca6c7cc72fecadcf/data/Multiple-choice_Questions/2010-2022_Math_I_MCQs.json#L18).
