### ISSUE TITLE
Typos in the dataset.

### ISSUE THREAD

**Issue by chengeharrison** [OpenLMLab/GAOKAO-Bench#20]
When I parsed the options in the MCQ dataset, I found the following typos. These typos didn't follow the correct format. Could you please fix it?

- [Option C](https://github.com/OpenLMLab/GAOKAO-Bench/blob/main/data/Multiple-choice_Questions/2010-2022_Chemistry_MCQs.json#L1228) missing in index 111 in 2010-2022_Chemistry_MCQs.json
![image](https://github.com/OpenLMLab/GAOKAO-Bench/assets/70520919/50aedf7e-3a7f-4bdb-b39d-b3a0a5b06537)

- [Option B](https://github.com/OpenLMLab/GAOKAO-Bench/blob/main/data/Multiple-choice_Questions/2012-2022_English_Cloze_Test.json#L247) missing "." after it in index 16 in 2012-2022_English_Cloze_Test.json
![image](https://github.com/OpenLMLab/GAOKAO-Bench/assets/70520919/44936813-859e-4316-9675-370a12872224)

- [Option G](https://github.com/OpenLMLab/GAOKAO-Bench/blob/main/data/Multiple-choice_Questions/2012-2022_English_Cloze_Test.json#L352) missing "." after it in index 23 in 2012-2022_English_Cloze_Test.json
![image](https://github.com/OpenLMLab/GAOKAO-Bench/assets/70520919/907e7889-3472-4219-8e69-c06d8234db09)

**Comment by zzzyyi** [comment]
Thank you for your correction! We've modified the format that you mentioned above:)
