### ISSUE TITLE
关于测试题目格式

### ISSUE THREAD

**Issue by jimmyzhang610** [OpenLMLab/GAOKAO-Bench#21]
请教个问题，除了gpt-3.5-turbo，其它开源模型在选择题上的得分情况都普通只有100多分，是不是与题目的格式有关系?对于multi_question_choice的题目，比如2010-2022_English_Fill_in_Blanks，每个题目里面有多个题，需要模型输出多个选项，但模型可能就无法理解，或者理解了，但是没有按照规定的格式输出。这种情况会都会导致评分偏低对吗？而对于single_choice的题目，大部分模型应该都可支持。所以分数的高低展示的不仅仅是模型知识问答的能力，也反应了模型对于数据集格式的理解程度？

**Comment by zzzyyi** [comment]
可以这样理解，一方面评测模型的知识能力，另一方面是模型遵循指令的能力，即是否能按照指定的格式进行回答。
