### ISSUE TITLE
Missing Question

### ISSUE THREAD

**Issue by MarigoldTechStriker** [OpenLMLab/GAOKAO-Bench#30]
乔治·华盛顿在 1787 年 3 月写给詹姆斯·麦迪逊的一封信中写道：“对现行制度进行彻底改革是必不可少的，任何有判断能力的人都不会否认——我用双手和真心希望这项工作能够得到全面的探讨。习俗。” “彻底改革”指的是什么？\nA. 消除联邦制度的缺陷。B. 建立三权制衡的共和制度。  \n C. 废除君主立宪制。D. 改变松散的联邦制度。 \n",
回答:D
年:2013

**Comment by zzzyyi** [comment]
Do you mean this [question]( https://github.com/OpenLMLab/GAOKAO-Bench/blob/df2e9667f39145848fb4466c50fe5210d54d0c8c/Data/Objective_Questions/2010-2022_History_MCQs.json#L554C9-L564C11)?
