### ISSUE TITLE
The evaluation result can't match the paper result

### ISSUE THREAD

**Issue by CoderBak** [OpenLMLab/GAOKAO-Bench#33]
We evaluated your `objective_bench.py` on `2010-2022_Physics_MCQs` dataset with openai api model `gpt-3.5-turbo` with `temperature=0.3`, `max_token=4096`, and we got the result `27.343%` , unable to match your result `41.1%` . We assume that answering completely correct = 6 points, partially correct = 3 points, and one error = 0 points. We calculated the total score gained $m$ and total score of problems $n$ and used $m/n$ as the result.

**Comment by CoderBak** [comment]
Also, we tested `gpt-3.5-turbo` on your dataset `2010-2022_Physics_MCQs` with our own script, and tried on different tempertures from 0 to 1 . We still got results near `28%`, a lot smaller than `41%`.

**Comment by zzzyyi** [comment]
1. Do you use the same prompt we provide in the [Obj_Prompt.json](https://github.com/OpenLMLab/GAOKAO-Bench/blob/df2e9667f39145848fb4466c50fe5210d54d0c8c/Bench/Obj_Prompt.json)?
2. The results of gpt-3.5-turbo in the paper comes from the 0301 checkpoint and we conducted the experiments in June, 2023. The model you used may be different from the one we used.
3. We evaluate the gpt-3.5-turbo on 2024.03.13, which refers to the gpt-3.5-turbo-0125 checkpoint according to the OpenAI. We use `temperature=0.3` and `max_token=4096`, and the scoring rate is 37.5%.

**Comment by CoderBak** [comment]
I re-evaluated the physics dataset with your script today, just as I did before, and the result was `50%`. It seems that because the size of the physics dataset is `64`, the result is more flexible than I had thought, so it's reasonable to get different results. Thank you for your reply!
