### ISSUE TITLE
是否支持其他开源模型本地调用，不是以apikey方式

### ISSUE THREAD

**Issue by jidandan666** [OpenLMLab/GAOKAO-Bench#35]

**Comment by zzzyyi** [comment]
支持的，不过您需要将模型的推理脚本按照https://github.com/OpenLMLab/GAOKAO-Bench/blob/main/Models/openai_gpt4.py 中的方式进行封装。如果需要更多细节可以联系我～

**Comment by jidandan666** [comment]
好的，多谢




707027845
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenLMLab/GAOKAO-Bench"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月14日(星期天) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenLMLab/GAOKAO-Bench] 是否支持其他开源模型本地调用，不是以apikey方式 (Issue #35)





 
支持的，不过您需要将模型的推理脚本按照https://github.com/OpenLMLab/GAOKAO-Bench/blob/main/Models/openai_gpt4.py 中的方式进行封装。如果需要更多细节可以联系我～

**Comment by jidandan666** [comment]
温度设置是0.3，可不可以告诉一下，实验中top_k设置的值是多少




707027845
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenLMLab/GAOKAO-Bench"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月14日(星期天) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenLMLab/GAOKAO-Bench] 是否支持其他开源模型本地调用，不是以apikey方式 (Issue #35)





 
支持的，不过您需要将模型的推理脚本按照https://github.com/OpenLMLab/GAOKAO-Bench/blob/main/Models/openai_gpt4.py 中的方式进行封装。如果需要更多细节可以联系我～

**Comment by jidandan666** [comment]
可以分享一下，除了温度其他的值的设置吗，top_p，top_k




707027845
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenLMLab/GAOKAO-Bench"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月14日(星期天) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenLMLab/GAOKAO-Bench] 是否支持其他开源模型本地调用，不是以apikey方式 (Issue #35)





 
支持的，不过您需要将模型的推理脚本按照https://github.com/OpenLMLab/GAOKAO-Bench/blob/main/Models/openai_gpt4.py 中的方式进行封装。如果需要更多细节可以联系我～
