### ISSUE TITLE
分数不一致

### ISSUE THREAD

**Issue by kekezhai** [OpenLMLab/GAOKAO-Bench#38]
Results/merge_score.json结果里（"Liberal-Arts_Total_score": 548.3,"Science_Total_score": 466.1）给出的gpt_4_0314计算的高考总分和models-score图表里的文理科总分485和447 为什么不一致呢 ？

**Comment by zzzyyi** [comment]
你好，这是因为我们的models-score图表中的文理科总分的主观题部分是人工评测的；而Results/merge_score.json中的总分的主观题部分是gpt评测的，因此两者不一致。merge_score.json的sub_correction_type和sub_teacher_model_name字段展示了主观题的评测者为gpt-4-1106-preview。
感谢您的关注～
